### ISSUE TITLE
Testando a Linguagem Markdown

### ISSUE THREAD

**Issue by manzi94** [gustavoguanabara/git-github#1809]
# Aula de Linguagem Markdown
***
## Podemos (~~e devemos~~) _*misturar*_ configurações!
***
### Lista de tarefas
- [x] Tarefa1
- [x] Tarefa2
- [ ] Tarefa3
- [ ] Tarefa4
***
### Tabela
Num | Nome | Nota
--- | --- | ---
1 | Ivan | 9,8
***
### Sobre comandos:
 - não entendo o comando `document.GetElementById()`;
 - Veja um trecho do meu programa em Python:
```
num = int(input('Digite um número: ))
if num % 2 == 0:
    print(f'O número {num} é PAR.)
else:
    print(f'O número {num} é ÍMPAR.)
```
***
# Obrigado, professor! 🖖

**Comment by LuizCordeiro04** [comment]
# Aula de linguagem ~Markdown~ do curso de _Git e GitHub._
## Teste de título 2
### Teste de título 3
***
_~Misturando~_ **_configurações_**.
***
### **Lista Numerada:**
1. Ponto 1
   1. Subponto 
2. Ponto 2
    1. Subponto
4. Ponto 3

### **Lista Demarcada;**
* Teste
* Teste
    * Teste
* Teste

### **Lista de Tarefas:**
- [x] Tarefa 1
- [ ] Tarefa 2
- [ ] Tarefa 3
***
### **Teste de Imagem:**

![pexels-hitarth-jadhav-220357 (1)](https://user-images.githubusercontent.com/109817203/181509021-1ca57501-58c1-4371-842e-9af122df25c9.jpg)
***
### **Teste de Links:**
[Acesse meu GitHub](https://github.com/LuizCordeiro04)
***
### __Teste de Tabelas:__
Num | Nome | Nota
---|---|---
1 | Luiz |  10
2 | Neto | 10
***
### **Teste de Programa:**
```
num = int(input('Digite um número: ))
if num % 2 == 0:
    print(f'O número {num} é PAR.)
else:
    print(f'O número {num} é ÍMPAR.)
```
***
### **Teste de Comando:**
Com certeza você conhece esse comando, ``System.out.println();``
***
### **Emojis:**
# Valeu grande Gafanhoto! 🖖🏾 😍

**Comment by magnowerbett** [comment]
# Follow me 
[~~Só clicar aqui~~](https://github.com/magnowerbett) 
Agradeço desde já! 🤜🤛

**Comment by thaliarrais** [comment]
## Estou aprendendo ~~Markdown~~ no Curso em Vídeo e GitHub
---
__*Podemos misturar formatações.*__

Lista numerada:

1. Teste
8. Teste 2
   1. Teste 3

Lista demarcada:
* Teste
* Teste
   * Teste

Lista de tarefas:
- [x] Tarefa 1.
- [ ] Tarefa 2.
![girasol imagem](https://user-images.githubusercontent.com/89674790/188254637-0274ae15-bb23-4335-8f6e-a32d544a8a44.jpg)

[Acesse o meu GitHub.](https://github.com/morenguinha)

Nome | Num | Nota
---|---|---
Thalia| 1 |10,0
Felipe| 2 |10,0

Linha de código: ` print("Hello World")`

Trecho de código:
```
printls("Hello World")
printls("Olá Mundo")
```
💛 💛 💛 

### Pergunta:
> Do que se trata esse comentário ?

Re: É um teste do guia de Markdown do Curso em Vídeo.

**Comment by caio-arcanjo** [comment]
# Aula de linguagem ~~Markdown~~
## Testando a linguagem Markdown dentro do Github, no navegador
---

Estou aprendendo linguaguem **Markdown** no Curso em Vídeo de Git e Github

1. Lista 1
2. Lista 2
   1. Sub item 
---

Lista demarcada:

* Teste com asterisco 
- Teste com traço

---

Lista de tarefas:

- [x] Criar página principal
- [x] Criar página da loja
- [ ] Apresentar ao cliente
- [ ] Finalizar o projeto inicial

---

## Colocando a Logo do meu canal no YouTube Minerando Jogos:


![logo](https://user-images.githubusercontent.com/81818536/189936930-e4295454-3970-454d-983b-8819d475e134.png)

[Acesse meu canal no Youtube](https://www.youtube.com/channel/UC56iX1tUn18lncfdcBW-n8g)

---

### Criando uma tabela:

Num | Nome | Nota
---|---|---
1 | Caio | 9,0
2 | Sthéfani | 9,5
3 | Lucas | 8,0

---

### Tirando uma dúvida de programação no Github

Não entendo o que faz o comando __`document.getElementById()`__ em linguagem JavaScript.
Podem me ajudar por favor?

Para colocar um trecho de código colocar __3 crases antes e 3 crases depois__:

```
Aqui vem o trecho do código!!! ✋ 
```

---

**Comment by BrawnerAlbuquerque** [comment]
## Teste Markdown :vulcan_salute: 
**Lista numerada:**
1. Elemento 1
   1. Subitem  1
   2. Subitem 2
---
**Lista demarcada:**
* Elemento 1
  * Subitem  1
* Subitem 2
---
**ToDo list:**
- [x] Tarefa 1
- [ ] Tarefa 2
---
__Imagem e links:__
![Cyberpunk edgerunners](https://pbs.twimg.com/profile_images/1526195974925864960/fVIw2avJ_400x400.jpg)

[Clique aqui](https://img.ifunny.co/images/5afc3f7e540faadb03b014e632b6de1a6302d946063e9e122ccc9aae1225316d_1.jpg)
---
__Tabelas:__
Nome | Nota
---|---
Braw | 10
---
**Comandos e trecho de código:**
`print("Hello World!")`
```
str = input(Diga algo:)
    print(f'Me disseram {str}.')
```
---
>repley
