### ISSUE TITLE
galera testando a linguagem MarkDown

### ISSUE THREAD

**Issue by amiltonaas** [gustavoguanabara/git-github#2502]
Aqui é para teste da linguagem markDown

**Comment by ronerio** [comment]
# Titulo 1
## Titulo 2
### Titulo 3

Coluna 1 | Coluna 2 | Coluna 3
---|---|---
Item 1 | Item 2 | Item 3
Item 4 | Item 5 | Item 6

_fim da tabela_
**fim da tabela**

✋ 🖖 😄   

Checklist
1. Ola
2. Ola 2
   1. Ola 3

Checlist 2
- Teste 1
- Teste 2
- Teste 3
   - teste4

**Comment by ronerio** [comment]
[não clique aqui](https://google.com.br)

**Comment by ronerio** [comment]
`getElementByID()`
```
nome = joao
nome2 = maria

print('{} e {} são um casal feliz'.format(nome, nome2))
```

**Comment by devjoaoribeiro** [comment]
Estou aprendendo __Markdown__  no Curso em Vídeo de Git e GitHub:
**Negrito** é com = 2** no inicio e fim ou 2__ 
~~coisas riscadas~~ = 1~ no inicio e fim
_itálico_  = 1* no inicio e fim ou 1_

# titulo de nível 1 = 1# no inicio e 01 espaço
## titulo de nível 2 = 2## no inicio e 01 espaço
### titulo de nível 3 e por ai vai = 3### no inicio e 01 espaço

uma linha abaixo bem demarcado usa 03*** ou 03--- sozinhos
*** 
---

***podemos misturar usando passos acima*** ex.: 3*** no inicio e fim

lista numerada:
1. você usa o numero e um ponto junto
   1.1 para vira sub item acrescente 03 espaços antes do num. 
lista demarcada:
*  usa um asterisco ou tracinho no inicio
   * para vira sub item acrescente 03 espaços antes do asterisco ou tracinho. 

lista de tarefas:
- [ ] usa traço, espaço, abre colchetes, espaço e fecha colchetes
- [x] mesmo comando de cima acrescentando o x no espaço vazio

**Comment by devjoaoribeiro** [comment]
> 

👍 👍 👍

**Comment by devjoaoribeiro** [comment]
> Estou aprendendo **Markdown** no Curso em Vídeo de Git e GitHub: **Negrito** é com = 2** no inicio e fim ou 2__ ~coisas riscadas~ = 1~ no inicio e fim _itálico_ = 1* no inicio e fim ou 1_
> 
> # titulo de nível 1 = 1# no inicio e 01 espaço
> ## titulo de nível 2 = 2## no inicio e 01 espaço
> ### titulo de nível 3 e por ai vai = 3### no inicio e 01 espaço
> uma linha abaixo bem demarcado usa 03*** ou 03--- sozinhos
> 
> _**podemos misturar usando passos acima**_ ex.: 3*** no inicio e fim
> 
> lista numerada:
> 
> 1. você usa o numero e um ponto junto
>    1.1 para vira sub item acrescente 03 espaços antes do num.
>    lista demarcada:
> 
> * usa um asterisco ou tracinho no inicio
>   
>   * para vira sub item acrescente 03 espaços antes do asterisco ou tracinho.
> 
> lista de tarefas:
> 
> * [ ]  usa traço, espaço, abre colchetes, espaço e fecha colchetes
> * [x]  mesmo comando de cima acrescentando o x no espaço vazio

| Coluna 1 | Coluna 2 |
|--------|--------|
| l1c1 | l1c2 |
| l2c1 | l2c2 | 

🥇 👍 @gustavoguanabara ótimo professor

**Comment by Carlos-niell** [comment]
#  Aula de linguagem Marksown
***
lista numerada:
1. Teste
2. Teste3
   

Lista demarcada
* teste
* teste

Lista de tarefas:
- [x]  Criar a pagina da loja
- [ ] Criar forma de pagamentos

**Comment by Carlos-niell** [comment]
![vidro galaxia](https://github.com/gustavoguanabara/git-github/assets/114493985/71599bb0-16cb-4009-8c25-027ab101c6af)

**Comment by Carlos-niell** [comment]
Num | Nome | Notas 
--- | --- | ---
1  | Daniel | 8.6
2 | Jose | 7.2 

termiou  tabela

**Comment by devcaina** [comment]
# Aula de MarkDown
***
podemos __*misturar*__ as paradas

Lista com Numeros:
1. arar
2. peido

Lista Demarcada:
* testei
* peidei
* caguei

Lista de Tarefas:

- [x] Peidar
- [x] Cagar na Sala
- [ ] Ganhar Dinheiro

Redes Sociais:

* Meu Perfil no [Instagram](https://instagram.com/devcainaa)
* Meu Repositorio no [GitHub](https://github.com/devcaina?tab=repositories)

**Comment by vitorgustavo04** [comment]
# Título
## Título
### Título
***
Lista numérica:

1. Lista
2. Lista
3. Lista
   1. Lista
***
Lista demarcada:

* Teste
* Teste
* Teste
   * Teste
***
Lista de Tarefas:

- [ ] Fazer
- [ ] Fazer
- [x] Fazer
***

Tabela:

Num | Nome | Nota
1 | Vitor | 10
2 | Vini | 8,9

**Comment by vitorgustavo04** [comment]
Olá pequeno gafanhoto :wave:

**Comment by RafaelPAlves88** [comment]
# **CURSO DE *GIT* E *GITHUB***

***
# TITULO
## TITULO
### TITULO
***

## **CAMPEONATO BRASILEIRO - 2023**

1. Botafogo - 27 Pts
   **Cidade:** Rio de Janeiro
   **Torcedores:** 2,77 Milhões

2. Palmeiras - 22 Pts
   ***Cidade:** São Paulo*
   ***Torcedeores:** 17 Milhões*

3. Grêmio - 20 Pts
   ***Cidade:** Porto Alegre*
   ***Torcedeores:** 10,3 Milhões*

4. Flamengo - 19 Pts
   ***Cidade:** Rio de Janeiro*
   ***Torcedeores:** 52,7 Milhões*

#### *[Fonte: Site Maiores e Melhores](https://maioresemelhores.com/maiores-torcidas-do-brasil)*

***

# RECEITA DE BOLO de Fubá

* 1/2 Xícara de Farinha de Fubá e assim por diante.

***

## DESAFIOS DO BEECROWD

- [ ] 40 EXERCÍCIOS EM PYTHON
- [ ] 20 EXERCÍCIOS EM JAVA
- [ ] 30 EXERCÍCISO EM SQL
***

[Acesse meu GitHub que está em fase de desenvolvimento](https://github.com/RafaelPAlves88)
![one-piece-unlimited-world-red-monkey-d-luffy-logo-piracy-luffy-57ddb44340caf0bc5b2a81f3624b8deb](https://github.com/gustavoguanabara/git-github/assets/117296683/88279e47-163f-4a95-970d-a27e5f4bf941)

***
## Criando uma Tabela - Notas de Alunos

Num | Nome | Notas
---|---|---
1 | Rafael | 8,5
2 | Daniele | 10
3 | Maria | 9

***

Não entendo o `Def` na linguagem Python

Meu programa em Python

```
num = int(input('Digite um nome: '))
if num < 0:
    print(f' {num} é negativo ')
else:
    print(f' {num} é positivo  ')
```

**Comment by Jonathan-Santos-Developer** [comment]
# testando a linguagem MarkDown
***
## Ênfase em textos:
Este **texto** *contém* __*ênfase*__
***
## Listas numeradas:
1. Primeiro item
1. segundo item
1. terceiro item
   1. sub item
   1. mais um sub item
***
## Listas demarcada:
* Primeiro item
* Segundo item
* terceito item
  * Sub item
  * Mais um
***
## Lista de tarefas:
- [ ] Primeira tarefa
- [x] Segunda tarefa
- [ ] Terceira tarefa  
   - [x] Quarta tarefa
   - [x] Quinta tarefa
   
***
## Tabelas
NUM | NAME | AGE 
---|---|---
1 | Jonathan | 25
2 | Ana | 23
3 | Pedro | 27
***
## Links 
[Acesse o meu GitHub] (https://github.com/JonathanSantos18)
***
## Code
`console.log(🥇)`

```
console.log(👍🏾) 

```

**Comment by ChrisCodever** [comment]
Teste de link 
Guitarrista Christian Orsogna Acesse @RafaelPAlves88 (teste)
[Clique Aqui](https://www.youtube.com/@ChristianOrsogna)
![logotipo Christian010](https://github.com/gustavoguanabara/git-github/assets/137825167/e8370e08-6054-4d48-9cf5-35312b96db1b)

**Comment by mdsjr** [comment]
# Título
## segundo nivel
---
Estou aprendendo linguagem _MarkDown_ no curso ~~Git~~ e GitHub

__*misturar configurações*__

1. teste
2. teste2
   1. teste 
   2. numerda
99. teste

Demarcada:

* teste

Lista de Tarefas:
- [ ] criar págia
- [x ] reunião
- [ ] vender


![download](https://github.com/gustavoguanabara/git-github/assets/59853005/ef7943ec-cb50-4b77-87d6-c60b224b761d)

acesse meu [linkedin](https://www.linkedin.com/in/moacirdsjr/)

Nome | Numero | Nota
---|---|---
1 | Moacir | 10

Olá pequeno gafanhoto 🖖 ⚽ 🤝 

Como diria @gustavoguanabara

**Comment by YuriLeocadio** [comment]
[clique aki...](https://www.cursoemvideo.com/curso/curso-de-git-e-github/aulas/aulas-de-git-e-github/modulos/guia-da-linguagem-markdown-curso-de-git-e-github/)

**Comment by YuriLeocadio** [comment]
# Yuri
## Yuri
### Yuri
---
~~Yuri~~
---
**Yuri**
---
* Yuri
---
__*Yuri*__
---
1. Yuri
1. Yuri2
1. Yuri3
---
1. Yuri
1. Yuri2
   1. Yuri3
1. Yuri
--- 
* Yuri
* Yuri2
   * Yuri3
   * Yuri4
---
- [ ] Yuri
- [x] Yuri
---
num | nome | nota | sla | slaw
---|---|---|---|---
1 | Yuri | 10,0 | 213 | 212
2 | Yuri2 | 9,5 | 453 | 798

**Comment by alex-nakahara** [comment]
Estou aprendendo linguagem **Markdown** no *Curso* ~~Pago~~ em Vídeo de *Git* e *GitHub*
---
Podemos __*Misturar*__ configurações
***
# Aula de Linguagem Markdown 
## Aula 9
### Aula 9

Lista Numerada:

1. Teste
   Sub Item sem numerar: 3 espaços

1. Teste 2
   Informações

3. Teste 3
   1. Sub Item numerado com 3 espaços

Lista Demarcada:

- Teste
* Teste
   * Teste

Lista de Tarefas:

- [ ] Tarefa para Realizar 
- [x] Tarefa Finalizada

[Acesse meu GitHub!](https://github.com/alex-nakahara)

Num | Nome | Nota
--- |---|---
1|Gustavo|8,5
2|Alex|9,0
3|Tayla|10,0

O comando `Palavra dentro da crase` faz ficar desta forma

Olha meu Programa em Pyton
```
num=int(input('Digite um Valor: ')
if num % 2 == 0:
   print(f'O valor {num} é PAR')
else:
   print(f'O valor {num} é ÍMPAR')
```
Olá, pequeno Gafanhoto 🖖 Emojes nesse [Link](github.com/ikatyang)
Para títulos, entrar nesse [Link](https://emojipedia.org/)

**Comment by anajulialeite** [comment]
# Aula de Linguagem Markdown
___
Estou aprendendo linguagem **markdown** no curso em vídeo de Git e Github
Podemos __*misturar*__ configurações

Lista numerada:
1. Teste
1. Teste2
   1. Teste1
   1. Teste2
1. Teste3

Lista demarcada:
* Teste
* Teste
   * Teste
* Teste

Lista de tarefas:
- [x] Criar a página principal 
- [x] Criar a página da loja
- [ ] Realizar a reunião com o cliente
- [ ] Receber pagamento

![03-lua-cheia](https://github.com/gustavoguanabara/git-github/assets/139260194/b010042e-ba4b-4c57-af31-ec9295e35552)

[Acesse o meu Github](https://github.com/anajulialeite)

Tabela:
NUM | NOME | NOTA
---|---|---|
1 | Ana Júlia | 84
2 | Gustavo | 100

Terminou a tabela

Comando:
Não entendo direito para que serve o comando `document.getElementById()` da linguagem JavaScript 

Trechos de comando:
Olha o meu programa em Python
```
num = int(input('Digite um valor: ')
if num % 2 == 0:
    print (f'O valor {num} é PAR')
else:
    print(f'O valor {num} é IMPAR)
```

Usando Emojis:
Olá, Pequeno Gafanhoto :vulcan_salute: :hand: :monkey:

Marcar e fazer citações:
Como diria  @Yasmin "o curso de SIS é muito longo"
> Será que vai chover ???

**Comment by anajulialeite** [comment]
> ## Estou aprendendo linguagem **Markdown** no _Curso_ ~pago~em Vídeo de _Git_ e _GitHub_
> Podemos **_Misturar_** configurações
> 
> # Aula de Linguagem Markdown
> ## Aula 9
> ### Aula 9
> Lista Numerada:
> 
> 1. Teste 
>    Sub Item sem numerar: 3 espaços
> 2. Teste 2 
>    Informações
> 3. Teste 3
>    
>    1. Sub Item numerado com 3 espaços
> 
> Lista Demarcada:
> 
> * teste
> 
> * teste
>   
>   * teste
> 
> Lista de Tarefas:
> 
> * [ ] Tarefa para Realizar
> * [x] Tarefa Finalizada
> 
> [Acesse meu GitHub!](https://github.com/alex-nakahara)
> 
> Num	Nome	Nota
> 1	Gustavo	8,5
> 2	Alex	9,0
> 3	tayla	10,0
> O comando `Palavra dentro da crase`faz ficar desta forma
> 
> Olha meu Programa em Pyton
> 
> ```
> num=int(input('Digite um Valor: ')
> if num % 2 == 0:
>    print(f'O valor {num} é PAR')
> else:
>    print(f'O valor {num} é ÍMPAR')
> ```
> 
> Olá, pequeno Gafanhoto🖖Emojes nesse [Link](github.com/ikatyang) Para títulos, entre nesse [Link](https://emojipedia.org/)

Muito legal a sua postagem!

**Comment by DougSNiiuchi** [comment]
# Titulo
## Título
### Título
---
***

Testando linguagem **Markdown** no Curso em Vídeo *Git-GitHub*

~~Teste~~

1. teste
2. teste
3. teste

* Teste
* Teste
  * Teste

- [x] Teste tarefa
- [ ] Teste tarefa

**Comment by DougSNiiuchi** [comment]
Nome | Numero | Nota
---|---|---
1 | Douglas | 9,0
2 | Chico | 1,0
3 | Antonia | 8,0

**Comment by DougSNiiuchi** [comment]
🖖

**Comment by Douglas1294** [comment]
# Aula de Linguagem Markdown
***
Podemos **Misturar**configurações

Lista numerada:
1. Teste
0. Teste 2
   1.Teste 1
   1.Teste 2
999. Teste 5

Lista demarcada:

* Teste
* Teste
* Teste
   * Teste
* Teste 



Liste de Tarefas:

- [ ] Criar a página principal
- [x] Criar página da loja
- [x] Finalizar a reunião com o cliente
- [ ] Receber pagamentos
![Imagem Github](https://github.com/gustavoguanabara/git-github/assets/113558017/23635a81-2a49-47ad-8e67-06df77826a92)


[Acesse meu GitHub](https://github.com/Douglas1294)


Num | Nome | Nota
---|---|---
1 | Douglas | 8.5
2 | Lucas | 5,0
3 | pedro | 10,00


Terminou a Tabela



Olha meu programa em Python
***

num = int(input('Digite um valor: ')
if num % 2 == 0:
    print(f' O valor {num} é PAR')
else:
    print(f' O valor {num} é ÍMPAR')
***

emogis

Olá, pequeno aluno :vulcan_salute:

**Comment by yanvferreira** [comment]
Galera testando linguagem __Markdown__
***
# Aula de linguagem Markdown
Lista numerada:
1. Teste
2. Teste2

Lista de Tarefa:
- [ ] Tarefa 1
- [x] Tarefa 2

**Comment by joaovgfreitas** [comment]
# Aula de Linguagem Markdown

Lista numerada:
1. Teste
2. Teste

Lista de não-ordenada:
* Teste 1
* Teste 2

Lista de Tarefas:
- [x] Teste 1
- [ ] Teste 2

[Acesse meu GitHub](https://github.com/joaovgfreitas)

Num | Nome | Nota
---|---|---
1 | João | 8,5
2 | Felipe | 9,0

Fim da Tabela!

**Comment by RafaelRobertoVS** [comment]
# Aula de Linguagem Markdown
***
Estou aprendendo linguagem **Markdown** no Curso em Video de Git e GitHub
***
Podemos __*misturar*__ configurações

Lista Numerada:
1. Teste
1. Teste2


Lista demarcada:
* Teste 
* Teste
* Teste
     * Teste

Lista de tarefas:
- [ ] Criar a página principal
- [ ] Criar página da loja
- [ ] Finalizar Reunião
- [x] Receber pagamento


**[Acesse meu GitHub](https://github.com/RafaelRobertoVS)**

Tabelas:

Num | Nome | Nota
---|---|---
1 | Rafael | 9.0
2 | Thalita | 10
Terminou a Tabela

**Olá, pequeno gafanhoto**  🖖🏻

**Comment by Laicram88** [comment]
# MARKDOWN
***
Estou aqui 3 anos depois do curso ter sido feito e aprendendo linguagem de programação __MarkDown__ no curso em video de Git e GitHub, com o grande gafanhoto

**Comment by F-Shouter** [comment]
# I'm tryind to lean  Markdown lenguage on the Git and GitHub video course.
---
## Task List:
- [x] HTML;
- [ ] CSS;
- [x] Git GitHub;
- [ ] Javascript;
---
## Images:

![capacete-de-astronauta2](https://github.com/gustavoguanabara/git-github/assets/132644949/38a2fc9c-2d57-453b-8ae3-88ad29b913c5)
---
## Links:
[Acess my profile](https://github.com/F-Shouter)
---
## Tables:
Num | Name | Grade
---|---|---
01 | Yukari | 9,4
10 | Guanabara | 99,9
20 | Will | 5,7
49 | Edygar | 8,5
---
## Codes:
```
num=int(input("Insert the number:"))
if num % 2 == 0:
    print(f' The value {num} is EVEN')
else:
    print(f' The value {num} is ODD')
```
---
## Emojis:
**smile** 😄  **cat** 🐱

**Comment by VinyTech** [comment]
# **Aula De Linguagem Markdown**
---
## Podemos  __*misturar*__ as configurações.
***
Lista numerada:

1. teste1
   sub1
   1. teste1
   1. teste2
   2. teste3
   3. teste4
2. teste2
3. teste3
---
Lista com marcadores:

* Teste
* teste 
   * teste
   * teste 
   * teste
* Teste
---
Lista de tarefas:

- [ ] Criar página principal.
- [ ] Almoçar pq já estou com fome.
- [x] Aprender o maximo possivpel de Git e GitHub
- [x] O professor __**Gustavo Guanabara**__ é ótimo no que faz!
---
![](https://user-images.githubusercontent.com/113558017/253690603-23635a81-2a49-47ad-8e67-06df77826a92.png)
Acesse meu GitHub clicando [**AQUI:**](https://github.com/VinyTech)
---
#  **TABELAS**

Número | Nome | Nota
---|---|---
1 | Gustavo | 9
2 | Viny | 10
3 | José | 8,5

# **Comandos**

 Não entendo direito para que serve o comando `document.getElementByld()` da linguagem JavaScript.

Olha meu programa em Python.
```
num = int(input('Digite um valor: ')
if num % 2 == 0:
    print(f' O valor {num} é Par')
else:
    print(f' O valor {num} é ÍMPAR')
```
![prog  Python](https://github.com/gustavoguanabara/git-github/assets/98596441/5e3af034-cc6c-4e92-b656-b3be9ab850db)

## **Emojis**

Olá pequeno gafanhoto :+1: 
:<html>
<body>


:earth_americas:
--

**Comment by JoaoVitorDomingos** [comment]
# Título
***
Testando a ~~linguagem~~ **_Markdown_**
## Listas
---
Lista Numerada:
1. Item1
2. Item2
   1. Item2.1
   2. Item2.2
55. Item3

Lista Demarcada:
* Item1
* Item2
   * Item2.2
* Item3

Lista de Tarefas:
- [x] Fazer o site
- [ ] Reunião com cliente
- [ ] Receber pagamento

### Imgs e Links
---
![download](https://github.com/gustavoguanabara/git-github/assets/127691953/5d724043-8b3b-47b6-96d2-ccda61801443)

[Acesse meu GitHub aqui](https://github.com/JoaoVitorDomingos)

#### Tabela
---
Número | Nome | Nota
---|---|---
1 | Maria | 10
2 | Jessica | 6
3 | Carlos | 3

#### Código:
---
Para que serve o comando `document.GetElementById()`

#### Bloco de Código:
***
Olha o meu programa em Python
```
num = int(input("Digite um valor:")
if num % 2 == 0:
    print(f`O valor {num} é PAR`)
else:
    print(f`O valor {num} é ÍMPAR`}
```

#### Emoji
***
👍 👎 💯 🔢 🥇 

#### Citações e Marcar Pessoas
---
Como diria @luisfabiano: entre bater o penaltil ou brigar, eu prefiro ajudar na briga

#### Respostas
---
> Como diria @luisfabiano: entre bater o penaltil ou brigar, eu prefiro ajudar na briga

Esse batia em!!!

**Comment by danilobonan** [comment]
# Aula de Markdown
### Teste da __*Linguagem*__ ~~**Markdown**~~

#### Tipos de Listas:

Lista numerada:

1. Fluminense
2. Vasco
3. Internacional
4. Palmeiras
5. Cruzeiro

Lista demarcada:

* Cores
   * Azul
   * Vermelho
   * Verde
* Instrumentos
   * Violão
   * Teclado
   * Bateria

Lista de tarefas:

- [ ] Enviar site para conferência
- [x] Criar o Readme
- [x] Criar a página secundária
- [ ] Salvar imagens utilizadas no programa
- [ ] Testar

***
#### Imagens e Links:

[Acesse meu GitHub](https://github.com/danilobonan)

![Deadpool](https://github.com/gustavoguanabara/git-github/assets/127451504/569b23ac-dba0-48ee-a1eb-095b606bcb04)
***

#### Tabelas:

Num | Nome | Nota
---|---|---
1 | Danilo | 10.00
2 | Bonan | 10.00
***

#### Comandos e Códigos:

`document.getElementById()`

```
<html>
   <body>
      <head>
         <h1>Página Teste</h1>
      </head>
   </body>
</html>
```

```
const number = 127
console.log(number)
```

```
p {
   padding: 15px
}
```

`let newVar = true`
***

#### Emojis:

Olá, pequenos Gafanhotos 🖖🏻 
Esse é meu teste de Markdown 😉 👍🏻 
Bora codar 💻
***

#### Citações:

Professor @gustavoguanabara é o cara!
***

>Isso é um quote?

Sim!

**Comment by mateusleguir** [comment]
<div align="center"><img src="https://icons.iconarchive.com/icons/simpleicons-team/simple/128/git-icon.png" alt="git" width="128" height="128" style="display:inline-block; margin-right: 10px;">

<img src="https://icons.iconarchive.com/icons/simpleicons-team/simple/128/github-icon.png" alt="github" width="128" height="128" style="display:inline-block;">
</div>

<div align="center">
<h1>Curso de Git e GitHub</h1>
</div>

Material do curso de **Git e Github**, disponivel gratuitamente no canal do **_CursoemVideo_** no [_Youtube_](https://www.youtube.com/watch?v=xEKo29OWILE&list=PLHz_AreHm4dm7ZULPAmadvNhH6vk9oNZA&ab_channel=CursoemV%C3%ADdeo).<br>

## Introdução a linguagem de marcação **MARKDOWN**:
<div align="center">
<img src="https://icons.iconarchive.com/icons/github/octicons/128/markdown-16-icon.png" width="128" height="128">
</div><br>

### Para destacar uma palavra ou frase como título:

Pode se utilizar pelo menos 3 níveis e tamanhos de título utilizando Hashtag(#).<br>

Para título(Nivel 1), geralmente usando para título principal se utiliza apenas 1 hashtag(#) no inicio da frase.<br>

Para título(Nivel 2) se utiliza 2 hashtag(##) no inicio da frase.<br>

Para título(Nivel 3) se utiliza 3 hashtag(###) no inicio da frase.<br>

Para destacar uma palavra em **Negrito**:<br>
Pode se utilizar asteriscos duplos(**) no inicio e no fim da palavra(ex. ** palavra colada nos asteriscos \*\*) ou pode se utilizar um underline no inicio e outro no fim da palavra(ex. _ palavra colada nos underlines _).<br>

Para destacar uma palavra em _Itálico_:<br>
Pode se utilizar apenas um asterisco(_) no inicio e no fim da palavra(ex. _ palavra colada nos asteriscos \*).<br>

Para destacar uma palavra ~~riscada~~:<br>
Pode se utilizar dois til(~) no inicio e no fim da palavra(ex. ~~ palavra colada nos til ~~).<br>

## Para dividir a página por linhas:

Pode se utilizar embaixo da palavra ou frase 3 traços(---) ou 3 asteriscos(\*\*\*).<br>

### Combinações:

Para misturar dois tipos de marcações como _*Itálico e negrito*_ na mesma palavra:<br>

Pode se utilizar em sequência 1 underline e 1 asterisco no inicio e no fim(ex. -\* \*- ) da frase ou utilizar 3 asteriscos ou 3 underlines no inicio e no fim da palavra(ex. **_ AlgumaPalavraAquiColadaNosAsteriscosOuUnderlines _**).<br>

### Listas:

Para utilizar lista **numerada**:

1. Teste
2. Teste2
3. Test3
4. Teste4
5. Teste5

Para configurar uma lista numerada basta utilizar no inicio um numero com ponto(1.) para listagem.<br>

Para utilizar lista **demarcada**:

- Teste
- Teste2
- Teste3
- Teste4
- Teste5

Para configurar uma lista demarcada basta utilizar no inicio um asterisco(\*) para listagem.<br>

É possivel tambem utilizar no lugar do asterisco(\*) na listagem demarcada um traço(-), irá demarcar da mesma forma.<br>

Para utilizar lista de **tarefas**:

- [x] Criar repositório no GitHub
- [x] Subir arquivos[***Pull***] do curso pelo GitHub Desktop
- [x] Configurar e editar[***commit***] o README.md
- [x] Habilitar o GitHub Pages no [meu repositório](https://mateusleguir.github.io/git-github/)
- [ ] Ficar rico com programação

Para configurar uma lista de tarefas basta utilizar no inicio um traço com abre e fecha colchetes(-[ ]) para listagem.<br>

### Imagens:

Para adicionar imagem no github utilizando **markdown** basta inserir o texto da imagem com ponto de exclamação e colchetes(![*Nome da imagem aqui*]) e o link da imagem ficará dentro de parenteses(_O link da imagem vai aqui_)<br>

No caso, a imagem aparecerá mais ou menos assim:<br>

<div align="center">
  <img src="https://octodex.github.com/images/Fintechtocat.png" width="250" height="250">

</div><br>


Para criar seu próprio **Octocat**(_Mascote GitHub_), basta acessar:
[My octocat](https://myoctocat.com/build-your-octocat/)<br>

### Links:

Para adicionar links, basta utilizar um **Texto para o link** entre colchetes[*Texto do link aqui dentro*] e o **link entre parenteses**( _URL aqui dentro_)(ex. [ repositório git-github ](https://github.com/gustavoguanabara/git-github))<br>

### Tabelas:

Para gerar uma tabela é necessário utilizar pipe( | ) para gerar as colunas entre os valores e 3 traços(---) embaixo da primeira linha da tabela.

Segue exemplo:

| Num | Nome    | Nota |
| --- | ------- | ---- |
| 1   | Gustavo | 8,5  |
| 2   | José    | 10,0 |
| 3   | Maria   | 9,0  |
| 4   | João    | 7,5  |
| 5   | Joana   | 9,75 |

_Terminou a tabela_

### Códigos:

Para mostrar um comando de alguma linguagem em destaque, se utliza crase no inicio e no fim do comando( `` ).<br>

_ex01._<br>

"Não entendo direito para que serve o comando `document.getElementById()` da linguagem JavaScript."<br>

Para mostrar um trecho de codigo destacado, se utiliza crases triplas no inicio e no fim do codigo( `````` ):<br>

_ex02._<br>

Olha meu programa em Python:

```
num = int(input('Digite um valor:'))
if num % 2 == 0:
    print(f'O valor {num} é PAR')
else:
    print(f'O valor {num} é IMPAR')

```

### Emojis:

Para inserir emojis no github, basta utilizar dois pontos antes e depois do nome do emoji(ex.  :NomeDoEmoji: )

ex.<br>

:vulcan_salute:
:hand:
:monkey:

Se quiser visualizar um repositório de emojis super legal e bem organizado da **@ikatyang**, acesse [emoji-cheat-sheet](https://github.com/ikatyang/emoji-cheat-sheet)
