### ISSUE TITLE
Aula de linguagem Markdown

### ISSUE THREAD

**Issue by renansquarecom** [gustavoguanabara/git-github#3020]
Estou aprendendo linguagem **Markdown** no Curso em Vídeo de Git e Github
# Aula de linguagem Markdown
***
Podemos __*misturar*__ configurções
***

Listas misturadas:
1. Teste 
2. Teste 2
    1. teste 2.1
4. Teste 3
***
Lista demarcada
* Teste
* Teste
* Teste
   * Teste
   * Teste
* Teste

***
Lista de Tarefas

- [x] Tarefa 1
- [] Tarefa 2
- [] Tarefa 3
- [] Tarefa 4

***
[Acesse meu Github](https://github.com/renansquarecom)

***

***
Num | Nome | Nota
---|---|---
1 | Gustavo | 8,5
2 | Maria | 9,7
3 | Renan | 10

***
Olha esse comando em Java
```
system.out.println("Olá, mundo!")

```
***
Testando emojis ✋ 🖖 😄  

***
Como diria @gafanhotos

**Comment by arianaleticiaaa** [comment]
Hello, good afternoon @renansquarecom! My name is Letícia and I'm also learning **Markdown** language through Git e GitHub Curso em Video classes. 

# Markdown Language Class

We can __*mix*__ settings: 

---

**Ordered List:**

1. Test One
2. Test Two
   1. Subentry 1
   2. Subentry 2
 3. Test Three

**Marked List:**

* Test One
* Test Two
   * Subentry 1
   * Subentry 2
* Test Three
---
**Task List:**

- [x] Create main page
- [x] Create store page
- [ ] Wrap up customer meeting
- [ ] Receive payment

---
![Hadouken](https://github.com/gustavoguanabara/git-github/assets/124189918/ccfbfb6b-9252-4090-b00d-799262535215)

---

[Acess my GitHub](https://github.com/arianaleticiaaa)

---

**Table:**

Num | Name | Grade
---|---|---
1 | Gustavo | 8.5
2 | Maria | 9.7
3 | Luis | 10

---

I don't quite understant what the `document.getElementById()` JavaScript command is for.

Take a look at my Phyton programm:

```
num = int(input('Insert a value: '))
if num % 2 == 0:
    print(f'The inserted value {num} is EVEN')
else:
    print(f'The inserted value {num} is ODD')
```

---

Hello, @gustavoguanabara! :vulcan_salute: :smile: :computer: :monkey:

---

Happy studying y'all! Bye! :smile:
